In [1]:
#Import numpy as np and print the version number#

In [2]:
import numpy as np
print(np.__version__)

1.16.5


In [3]:
#Create a 1D array of numbers from 0 to 9#

In [4]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Create a 3×3 numpy array of all True’s#

In [10]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
#Extract all odd numbers from arr#

In [12]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [13]:
#Replace all odd numbers in arr with -1#

In [16]:
arr=np.arange(10)
arr[arr%2==1]=-1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
#Convert a 1D array to a 2D array with 2 rows#

In [19]:
arr=np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
 #Stack arrays a and b vertically#

In [22]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
#Stack the arrays a and b horizontally.#

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
 #Create the following pattern without hardcoding. Use only numpy functions and the below input array a.#

In [27]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
#Get the common items between a and b#

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [1]:
#From array a remove all items present in array b#

In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [ ]:
#Get the positions where elements of a and b match#

In [8]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [9]:
#Get all items between 5 and 10 from a.#

In [12]:
np.arange(15)
index=np.where((a>=5) & (a<=10))
a[index]

array([5, 6])

In [1]:
#Convert the function maxx that works on two scalars, to work on two arrays.#

In [23]:
import numpy as np
def maxx(x,y):
    #Get the maximum of two items#
    if x >= y:
            return x
    else:
            return y
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
    
    

array([6., 7., 9., 8., 9., 7., 5.])

In [24]:
#Swap columns 1 and 2 in the array arr.#

In [25]:
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [26]:
#Reverse the rows of a 2D array arr.#

In [28]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [29]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.#

In [33]:
import numpy as np
arr = np.arange(9).reshape(3,3)
randd_arr=np.random.uniform(5,10,size=(5,3))
print(randd_arr)

[[9.21513642 8.94744745 6.30923375]
 [9.53002176 9.07095957 7.12795385]
 [6.2870083  8.19986732 5.77734383]
 [5.00111028 6.37470365 5.77909067]
 [7.14464768 7.73821196 9.7857131 ]]


In [34]:
#Limit the number of items printed in python numpy array a to a maximum of 6 elements.#

In [35]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [ ]:
#Convert array_of_arrays into a flat linear 1d array.#

In [40]:
import numpy as np
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 ... 7 8 9]


In [ ]:
#Compute the one-hot encodings (dummy binary variables for each unique value in the array)#


In [44]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out
one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [45]:
#Find the 5th and 95th percentile of iris's sepallength#

In [47]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [48]:
#Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.#

In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
S = (sepallength - Smin)/sepallength.ptp()  # Thanks, David Ojeda!
print(S)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [3]:
#Select the rows of iris_2d that does not have any nan value.#

In [4]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [5]:
#Find out if iris_2d has any missing values.#

In [6]:
import numpy as np
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

In [7]:
#Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:#

   # Less than 3 --> 'small'
    #3-5 --> 'medium'
    #'>=5 --> 'large'#

In [8]:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [9]:
#Randomly sample iris's species such that setose is twice the number of versicolor and virginica#

In [10]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species = iris[:, 4]
# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36], dtype=int64))


In [11]:
#Sort the iris dataset based on sepallength column.#

In [12]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


In [13]:
#From the array a, replace all values greater than 30 to 30 and less than 10 to 10.#

In [14]:
import numpy as np
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a, a_min=10, a_max=30)
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [15]:
 #Compute the counts of unique values row-wise.#

In [16]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [17]:
#compute the one-hot encodings (dummy binary variables for each unique value in the array)#

In [18]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [19]:
#Create the ranks for the given numeric array a.#

In [20]:
import numpy as np
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)
print(a.argsort().argsort())
print('Array: ', a)

Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [21]:
#Compute the maximum for each row in the given array.#

In [23]:
import numpy as np
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
np.amax(a, axis=1)
np.apply_along_axis(np.max, arr=a, axis=1)

array([9, 8, 6, 3, 9])

In [24]:
#Drop all nan values from a 1D numpy array#

In [25]:
import numpy as np
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [26]:
#Compute the euclidean distance between two arrays a and b.#

In [27]:
import numpy as np
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

In [28]:
#Find the index of 5th repetition of number 1 in x.#

In [29]:
import numpy as np
dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.tolist()
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [30]:
#Compute the moving average of window size 3, for the given 1D array.#

In [32]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)
moving_average(Z, n=3).round(2)

array:  [8 8 3 7 7 0 4 2 5 2]


array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])